In [2]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib

In [74]:
import pandas as pd
import numpy as np
import matplotlib as plt
events = pd.read_csv("/Users/blaisepage/Documents/CUBoulder/DataMining/Final_Project/retrosheet-events-1970-2015/retrosheet-events-plus-woba-2005_2015.csv")
altitudes = pd.read_excel("/Users/blaisepage/Documents/CUBoulder/DataMining/Final_Project/MLB_Stadium_Altitudes.xlsx")
#Reading the dataset into a dataframe
#doesn't print anything

In [64]:
# event_cd codes:
# 23 => Homerun
# 22 => Triple
# 21 => Double
# 20 => Single

events_with_altitudes = pd.merge(events, altitudes, on='home_team_id')
events_with_altitudes.head(10)

,game_id,year_id,away_team_id,home_team_id,bat_id,pit_id,bat_home_id,event_cd,wOBA_pts,time_since_1900,...,inn_pa_ct,pit_start_fl,pa_ball_ct,pa_strike_ct,event_runs_ct,bat_fate_id,run1_fate_id,run2_fate_id,run3_fate_id,altitude
0,ANA200504050,2005,TEX,ANA,soria001,colob001,0,21,1.252,3.321714e+09,...,0,T,1,1,0,0,0,0,0,160
1,ANA200504050,2005,TEX,ANA,blalh001,colob001,0,14,0.703,3.321714e+09,...,1,T,4,0,0,0,0,0,0,160
2,ANA200504050,2005,TEX,ANA,younm003,colob001,0,2,0.000,3.321714e+09,...,2,T,2,4,0,0,0,0,0,160
3,ANA200504050,2005,TEX,ANA,teixm001,colob001,0,3,0.000,3.321714e+09,...,3,T,2,4,0,0,0,0,0,160
4,ANA200504050,2005,TEX,ANA,hidar001,colob001,0,2,0.000,3.321714e+09,...,4,T,0,3,0,0,0,0,0,160
5,ANA200504050,2005,TEX,ANA,erstd001,dresr001,1,14,0.703,3.321714e+09,...,0,T,4,2,0,0,0,0,0,160
6,ANA200504050,2005,TEX,ANA,davaj001,dresr001,1,2,0.000,3.321714e+09,...,1,T,0,1,0,0,0,0,0,160
7,ANA200504050,2005,TEX,ANA,guerv001,dresr001,1,23,2.017,3.321715e+09,...,2,T,2,1,1,4,0,0,0,160
8,ANA200504050,2005,TEX,ANA,andeg001,dresr001,1,20,0.890,3.321715e+09,...,3,T,0,1,0,0,0,0,0,160
9,ANA200504050,2005,TEX,ANA,finls001,dresr001,1,2,0.000,3.321715e+09,...,4,T,0,2,0,0,0,0,0,160

In [5]:
# calculate which events each stadium best facillitates
'''
1    No event
2    Generic out
3    Strikeout
4    Stolen base
5    Defensive indifference
6    Caught stealing
7    Pickoff error
8    Pickoff
9    Wild pitch
10   Passed ball
11   Balk
12   Other advance
13   Foul error
14   Walk
15   Intentional walk
16   Hit by pitch
17   Interference
18   Error
19   Fielder's choice
20   Single
21   Double
22   Triple
23   Home run
'''

altitudes.head(30)

event_counts = [[0]*(24) for i in range(0,31)]

#for i in range(1,30):
#    event_counts[1][i] = 1

#print len(event_counts)
#event_counts[29][23] = 1
#print event_counts

for i in range(0,31):
    event_counts[i][0] = altitudes['home_team_id'][i]
    
for i in range(0,2111526):   
    for j in range(0,31):
    
        if(event_counts[j][0] == events_with_altitudes['home_team_id'][i]):
        
            event_counts[j][events_with_altitudes['event_cd'][i]] += 1
    

print event_counts

[[u'TEX', 0, 32946, 11988, 964, 129, 283, 0, 194, 614, 98, 46, 24, 13, 5356, 319, 646, 18, 706, 194, 11039, 3328, 356, 2069], [u'ANA', 0, 33084, 12191, 1082, 136, 340, 0, 233, 601, 87, 44, 28, 19, 4793, 392, 558, 19, 611, 217, 10865, 3029, 246, 1641], [u'BAL', 0, 33658, 11649, 797, 77, 279, 0, 133, 452, 96, 60, 20, 19, 5224, 335, 598, 11, 539, 148, 11011, 3123, 206, 2211], [u'DET', 0, 33139, 11760, 758, 95, 272, 0, 227, 577, 87, 64, 35, 29, 5048, 420, 526, 7, 590, 174, 11227, 3067, 492, 1811], [u'BOS', 0, 32294, 12591, 966, 128, 213, 0, 169, 561, 161, 61, 24, 18, 5706, 348, 662, 7, 604, 156, 10648, 4072, 292, 1767], [u'CLE', 0, 32311, 12812, 897, 101, 298, 0, 178, 545, 122, 49, 27, 9, 5323, 343, 603, 5, 607, 189, 10598, 3349, 213, 1696], [u'KCA', 0, 33890, 11043, 935, 113, 302, 0, 239, 660, 101, 76, 37, 20, 4986, 306, 598, 8, 567, 206, 11369, 3441, 442, 1452], [u'OAK', 0, 33653, 11847, 870, 112, 217, 0, 179, 491, 107, 49, 27, 41, 5476, 326, 486, 4, 611, 191, 10179, 2934, 284, 1518], [u'MIN', 0, 33690, 11415, 885, 107, 251, 0, 178, 528, 94, 54, 23, 6, 4620, 343, 499, 1, 571, 204, 11307, 3171, 374, 1603], [u'TOR', 0, 32849, 12505, 883, 85, 213, 0, 202, 455, 134, 47, 26, 18, 5202, 294, 662, 9, 576, 158, 9829, 3461, 312, 2124], [u'SEA', 0, 32883, 12753, 871, 109, 305, 0, 189, 568, 107, 50, 27, 13, 4858, 376, 537, 4, 563, 185, 10409, 2847, 214, 1593], [u'TBA', 0, 32006, 13393, 1140, 146, 334, 0, 202, 577, 119, 52, 33, 12, 5517, 338, 673, 17, 509, 142, 9968, 2886, 361, 1799], [u'CHA', 0, 32686, 12682, 1036, 84, 291, 0, 237, 618, 113, 57, 34, 24, 5185, 378, 659, 7, 615, 132, 10520, 2876, 229, 2148], [u'NYA', 0, 32418, 12610, 1064, 118, 264, 0, 161, 542, 105, 64, 26, 12, 5557, 337, 718, 10, 608, 156, 10657, 3004, 207, 2222], [u'SFN', 0, 33114, 12270, 915, 94, 308, 0, 175, 577, 87, 44, 24, 7, 4950, 506, 476, 10, 589, 213, 10314, 3059, 470, 1260], [u'SLN', 0, 33661, 11511, 589, 99, 266, 0, 160, 494, 97, 41, 17, 13, 4947, 492, 640, 5, 620, 217, 10944, 3092, 282, 1492], [u'ARI', 0, 32532, 12855, 783, 104, 243, 0, 221, 617, 108, 56, 27, 8, 5196, 446, 585, 8, 546, 193, 10316, 3498, 508, 1896], [u'PHI', 0, 32674, 13038, 981, 111, 225, 0, 151, 463, 112, 63, 27, 25, 5025, 547, 698, 9, 651, 163, 10320, 3194, 322, 2045], [u'COL', 0, 33048, 11852, 989, 120, 259, 0, 229, 556, 106, 69, 38, 18, 5338, 542, 582, 8, 608, 217, 11815, 3652, 576, 2035], [u'LAN', 0, 32312, 13021, 1027, 138, 318, 0, 188, 496, 69, 57, 20, 19, 4938, 542, 546, 9, 583, 170, 10388, 2902, 208, 1546], [u'MIA', 0, 11834, 4735, 345, 35, 92, 0, 71, 170, 41, 14, 15, 5, 1733, 176, 159, 5, 166, 90, 3899, 1038, 177, 412], [u'FLO', 0, 20067, 8975, 584, 31, 206, 0, 118, 381, 77, 40, 18, 13, 3704, 406, 448, 3, 414, 125, 6686, 2069, 265, 1070], [u'CIN', 0, 32402, 13350, 850, 110, 267, 0, 193, 512, 91, 59, 18, 12, 5309, 473, 683, 9, 548, 200, 10152, 3179, 237, 2243], [u'MIL', 0, 31812, 13512, 929, 92, 255, 0, 215, 562, 60, 53, 22, 12, 5284, 435, 608, 8, 642, 185, 9917, 3186, 322, 2082], [u'HOU', 0, 32186, 13254, 915, 72, 282, 0, 171, 483, 114, 62, 35, 11, 4984, 428, 604, 9, 576, 189, 10194, 3062, 353, 1899], [u'SDN', 0, 32385, 13745, 1129, 112, 300, 0, 213, 376, 128, 51, 27, 7, 5291, 486, 493, 9, 509, 188, 9761, 2631, 384, 1414], [u'PIT', 0, 33340, 12155, 899, 82, 295, 0, 233, 522, 85, 42, 28, 12, 4951, 486, 712, 5, 641, 223, 10869, 3266, 297, 1435], [u'WAS', 0, 32978, 12507, 824, 91, 257, 0, 173, 521, 95, 63, 27, 18, 4966, 500, 606, 4, 612, 189, 10544, 3105, 279, 1581], [u'NYN', 0, 33134, 12751, 1015, 82, 241, 0, 151, 430, 99, 59, 25, 24, 5221, 566, 595, 5, 620, 179, 10135, 2976, 303, 1606], [u'ATL', 0, 32116, 13291, 848, 88, 259, 0, 164, 470, 103, 65, 17, 9, 5323, 581, 518, 19, 635, 157, 10544, 2995, 304, 1593], [u'CHN', 0, 31762, 13654, 905, 120, 299, 0, 172, 555, 109, 38, 36, 18, 5393, 417, 638, 5, 677, 201, 10057, 3183, 345, 1862]]

In [75]:
# combine event counts for florida and miami
new_row = []
new_row.append("MIA+FLO")
for i in range(1,24):
    count_sum = event_counts[20][i]+event_counts[21][i]
    new_row.append(count_sum)
    
event_counts.append(new_row)

#print event_counts

event_counts2 = []
for i in range(0,32):
    if i!=20 and i!=21:
        event_counts2.append(event_counts[i])
        
    
print event_counts2

# concat the combined MIA+FLO with altitudes array
df2 = pd.DataFrame({'home_team_id': ['MIA+FLO'],
                   'altitude': [altitudes['altitude'][20]]}
                   ,index=[32])

frames = [altitudes,df2]
altitudes = pd.concat(frames)

# Drop MIA and FLO individual stats
altitudes = altitudes[altitudes.home_team_id != 'MIA']
altitudes = altitudes[altitudes.home_team_id != 'FLO']

print altitudes

[[u'TEX', 0, 32946, 11988, 964, 129, 283, 0, 194, 614, 98, 46, 24, 13, 5356, 319, 646, 18, 706, 194, 11039, 3328, 356, 2069], [u'ANA', 0, 33084, 12191, 1082, 136, 340, 0, 233, 601, 87, 44, 28, 19, 4793, 392, 558, 19, 611, 217, 10865, 3029, 246, 1641], [u'BAL', 0, 33658, 11649, 797, 77, 279, 0, 133, 452, 96, 60, 20, 19, 5224, 335, 598, 11, 539, 148, 11011, 3123, 206, 2211], [u'DET', 0, 33139, 11760, 758, 95, 272, 0, 227, 577, 87, 64, 35, 29, 5048, 420, 526, 7, 590, 174, 11227, 3067, 492, 1811], [u'BOS', 0, 32294, 12591, 966, 128, 213, 0, 169, 561, 161, 61, 24, 18, 5706, 348, 662, 7, 604, 156, 10648, 4072, 292, 1767], [u'CLE', 0, 32311, 12812, 897, 101, 298, 0, 178, 545, 122, 49, 27, 9, 5323, 343, 603, 5, 607, 189, 10598, 3349, 213, 1696], [u'KCA', 0, 33890, 11043, 935, 113, 302, 0, 239, 660, 101, 76, 37, 20, 4986, 306, 598, 8, 567, 206, 11369, 3441, 442, 1452], [u'OAK', 0, 33653, 11847, 870, 112, 217, 0, 179, 491, 107, 49, 27, 41, 5476, 326, 486, 4, 611, 191, 10179, 2934, 284, 1518], [u'MIN', 0, 33690, 11415, 885, 107, 251, 0, 178, 528, 94, 54, 23, 6, 4620, 343, 499, 1, 571, 204, 11307, 3171, 374, 1603], [u'TOR', 0, 32849, 12505, 883, 85, 213, 0, 202, 455, 134, 47, 26, 18, 5202, 294, 662, 9, 576, 158, 9829, 3461, 312, 2124], [u'SEA', 0, 32883, 12753, 871, 109, 305, 0, 189, 568, 107, 50, 27, 13, 4858, 376, 537, 4, 563, 185, 10409, 2847, 214, 1593], [u'TBA', 0, 32006, 13393, 1140, 146, 334, 0, 202, 577, 119, 52, 33, 12, 5517, 338, 673, 17, 509, 142, 9968, 2886, 361, 1799], [u'CHA', 0, 32686, 12682, 1036, 84, 291, 0, 237, 618, 113, 57, 34, 24, 5185, 378, 659, 7, 615, 132, 10520, 2876, 229, 2148], [u'NYA', 0, 32418, 12610, 1064, 118, 264, 0, 161, 542, 105, 64, 26, 12, 5557, 337, 718, 10, 608, 156, 10657, 3004, 207, 2222], [u'SFN', 0, 33114, 12270, 915, 94, 308, 0, 175, 577, 87, 44, 24, 7, 4950, 506, 476, 10, 589, 213, 10314, 3059, 470, 1260], [u'SLN', 0, 33661, 11511, 589, 99, 266, 0, 160, 494, 97, 41, 17, 13, 4947, 492, 640, 5, 620, 217, 10944, 3092, 282, 1492], [u'ARI', 0, 32532, 12855, 783, 104, 243, 0, 221, 617, 108, 56, 27, 8, 5196, 446, 585, 8, 546, 193, 10316, 3498, 508, 1896], [u'PHI', 0, 32674, 13038, 981, 111, 225, 0, 151, 463, 112, 63, 27, 25, 5025, 547, 698, 9, 651, 163, 10320, 3194, 322, 2045], [u'COL', 0, 33048, 11852, 989, 120, 259, 0, 229, 556, 106, 69, 38, 18, 5338, 542, 582, 8, 608, 217, 11815, 3652, 576, 2035], [u'LAN', 0, 32312, 13021, 1027, 138, 318, 0, 188, 496, 69, 57, 20, 19, 4938, 542, 546, 9, 583, 170, 10388, 2902, 208, 1546], [u'CIN', 0, 32402, 13350, 850, 110, 267, 0, 193, 512, 91, 59, 18, 12, 5309, 473, 683, 9, 548, 200, 10152, 3179, 237, 2243], [u'MIL', 0, 31812, 13512, 929, 92, 255, 0, 215, 562, 60, 53, 22, 12, 5284, 435, 608, 8, 642, 185, 9917, 3186, 322, 2082], [u'HOU', 0, 32186, 13254, 915, 72, 282, 0, 171, 483, 114, 62, 35, 11, 4984, 428, 604, 9, 576, 189, 10194, 3062, 353, 1899], [u'SDN', 0, 32385, 13745, 1129, 112, 300, 0, 213, 376, 128, 51, 27, 7, 5291, 486, 493, 9, 509, 188, 9761, 2631, 384, 1414], [u'PIT', 0, 33340, 12155, 899, 82, 295, 0, 233, 522, 85, 42, 28, 12, 4951, 486, 712, 5, 641, 223, 10869, 3266, 297, 1435], [u'WAS', 0, 32978, 12507, 824, 91, 257, 0, 173, 521, 95, 63, 27, 18, 4966, 500, 606, 4, 612, 189, 10544, 3105, 279, 1581], [u'NYN', 0, 33134, 12751, 1015, 82, 241, 0, 151, 430, 99, 59, 25, 24, 5221, 566, 595, 5, 620, 179, 10135, 2976, 303, 1606], [u'ATL', 0, 32116, 13291, 848, 88, 259, 0, 164, 470, 103, 65, 17, 9, 5323, 581, 518, 19, 635, 157, 10544, 2995, 304, 1593], [u'CHN', 0, 31762, 13654, 905, 120, 299, 0, 172, 555, 109, 38, 36, 18, 5393, 417, 638, 5, 677, 201, 10057, 3183, 345, 1862], ['MIA+FLO', 0, 31901, 13710, 929, 66, 298, 0, 189, 551, 118, 54, 33, 18, 5437, 582, 607, 8, 580, 215, 10585, 3107, 442, 1482]]
    altitude home_team_id
0        616          TEX
1        160          ANA
2        130          BAL
3        594          DET
4         20          BOS
5        582          CLE
6        750          KCA
7         42          OAK
8        812          MIN
9        247          TOR
10        10          SEA
11        44          TBA
12       587          CHA
13        54          NYA
14        63          SFN
15       455          SLN
16      1082          ARI
17         9          PHI
18      5183          COL
19       267          LAN
22       683          CIN
23       593          MIL
24        38          HOU
25        13          SDN
26       743          PIT
27        25          WAS
28        53          NYN
29      1050          ATL
30       604          CHN
32        15      MIA+FLO

In [77]:
# fix indices
altitudes = altitudes.reset_index(drop=True)
print altitudes

    altitude home_team_id
0        616          TEX
1        160          ANA
2        130          BAL
3        594          DET
4         20          BOS
5        582          CLE
6        750          KCA
7         42          OAK
8        812          MIN
9        247          TOR
10        10          SEA
11        44          TBA
12       587          CHA
13        54          NYA
14        63          SFN
15       455          SLN
16      1082          ARI
17         9          PHI
18      5183          COL
19       267          LAN
20       683          CIN
21       593          MIL
22        38          HOU
23        13          SDN
24       743          PIT
25        25          WAS
26        53          NYN
27      1050          ATL
28       604          CHN
29        15      MIA+FLO

In [90]:
# init generic outs array
generic_outs_array = [[None]*(3) for i in range(0,30)]

for i in range(0,30):
    generic_outs_array[i][0] = altitudes['home_team_id'][i]
    generic_outs_array[i][1] = altitudes['altitude'][i]
    generic_outs_array[i][2] = event_counts2[i][2]

    
# calculate min/max generic outs (2)

print "GENERIC OUTS by STADIUMS: "
print " "

min_generic_outs = float('inf')
min_generic_outs_stadium = None
max_generic_outs = -1
max_generic_outs_stadium = None

for i in range(0,30):
    
    if(event_counts2[i][2] <= min_generic_outs):
        min_generic_outs = event_counts2[i][2]
        min_generic_outs_stadium = event_counts2[i][0]
        
    if(event_counts2[i][2] >= max_generic_outs):
        max_generic_outs = event_counts2[i][2]
        max_generic_outs_stadium = event_counts2[i][0]
        
    print "Stadium: ", event_counts2[i][0], " => ", event_counts2[i][2]
        
print " "
print "Max Generic Outs: ", max_generic_outs_stadium, " => ", max_generic_outs
print "Min Generic Outs: ", min_generic_outs_stadium, " => ", min_generic_outs

GENERIC OUTS by STADIUMS:

Stadium:  TEX  =>  32946
Stadium:  ANA  =>  33084
Stadium:  BAL  =>  33658
Stadium:  DET  =>  33139
Stadium:  BOS  =>  32294
Stadium:  CLE  =>  32311
Stadium:  KCA  =>  33890
Stadium:  OAK  =>  33653
Stadium:  MIN  =>  33690
Stadium:  TOR  =>  32849
Stadium:  SEA  =>  32883
Stadium:  TBA  =>  32006
Stadium:  CHA  =>  32686
Stadium:  NYA  =>  32418
Stadium:  SFN  =>  33114
Stadium:  SLN  =>  33661
Stadium:  ARI  =>  32532
Stadium:  PHI  =>  32674
Stadium:  COL  =>  33048
Stadium:  LAN  =>  32312
Stadium:  CIN  =>  32402
Stadium:  MIL  =>  31812
Stadium:  HOU  =>  32186
Stadium:  SDN  =>  32385
Stadium:  PIT  =>  33340
Stadium:  WAS  =>  32978
Stadium:  NYN  =>  33134
Stadium:  ATL  =>  32116
Stadium:  CHN  =>  31762
Stadium:  MIA+FLO  =>  31901

Max Generic Outs:  KCA  =>  33890
Min Generic Outs:  CHN  =>  31762

In [91]:
# init strikeouts array
strikeouts_array = [[None]*(3) for i in range(0,30)]

for i in range(0,30):
    strikeouts_array[i][0] = altitudes['home_team_id'][i]
    strikeouts_array[i][1] = altitudes['altitude'][i]
    strikeouts_array[i][2] = event_counts2[i][3]


# calculate min/max strikeouts (3)

print "STRIKEOUTS by STADIUMS: "
print " "

min_strikeouts = float('inf')
min_strikeouts_stadium = None
max_strikeouts = -1
max_strikeouts_stadium = None

for i in range(0,30):
    
    if(event_counts2[i][3] <= min_strikeouts):
        min_strikeouts = event_counts2[i][3]
        min_strikeouts_stadium = event_counts2[i][0]
        
    if(event_counts2[i][3] >= max_strikeouts):
        max_strikeouts = event_counts2[i][3]
        max_strikeouts_stadium = event_counts2[i][0]
        
    print "Stadium: ", event_counts2[i][0], " => ", event_counts2[i][3]
        
print " "
print "Max Srikeouts: ", max_strikeouts_stadium, " => ", max_strikeouts
print "Min Strikeouts: ", min_strikeouts_stadium, " => ", min_strikeouts

STRIKEOUTS by STADIUMS:

Stadium:  TEX  =>  11988
Stadium:  ANA  =>  12191
Stadium:  BAL  =>  11649
Stadium:  DET  =>  11760
Stadium:  BOS  =>  12591
Stadium:  CLE  =>  12812
Stadium:  KCA  =>  11043
Stadium:  OAK  =>  11847
Stadium:  MIN  =>  11415
Stadium:  TOR  =>  12505
Stadium:  SEA  =>  12753
Stadium:  TBA  =>  13393
Stadium:  CHA  =>  12682
Stadium:  NYA  =>  12610
Stadium:  SFN  =>  12270
Stadium:  SLN  =>  11511
Stadium:  ARI  =>  12855
Stadium:  PHI  =>  13038
Stadium:  COL  =>  11852
Stadium:  LAN  =>  13021
Stadium:  CIN  =>  13350
Stadium:  MIL  =>  13512
Stadium:  HOU  =>  13254
Stadium:  SDN  =>  13745
Stadium:  PIT  =>  12155
Stadium:  WAS  =>  12507
Stadium:  NYN  =>  12751
Stadium:  ATL  =>  13291
Stadium:  CHN  =>  13654
Stadium:  MIA+FLO  =>  13710

Max Srikeouts:  SDN  =>  13745
Min Strikeouts:  KCA  =>  11043

In [92]:
# init stolen base array
stolen_base_array = [[None]*(3) for i in range(0,30)]

for i in range(0,30):
    stolen_base_array[i][0] = altitudes['home_team_id'][i]
    stolen_base_array[i][1] = altitudes['altitude'][i]
    stolen_base_array[i][2] = event_counts2[i][4]

    
# calculate min/max stolen base (4)

print "STOLEN BASES by STADIUMS: "
print " "

min_stolen_base = float('inf')
min_stolen_base_stadium = None
max_stolen_base = -1
max_stolen_base_stadium = None

for i in range(0,30):
    
    if(event_counts2[i][4] <= min_stolen_base):
        min_stolen_base = event_counts2[i][4]
        min_stolen_base_stadium = event_counts2[i][0]
        
    if(event_counts2[i][4] >= max_stolen_base):
        max_stolen_base = event_counts2[i][4]
        max_stolen_base_stadium = event_counts2[i][0]
        
    print "Stadium: ", event_counts2[i][0], " => ", event_counts2[i][4]
        
print " "
print "Max Stolen Bases: ", max_stolen_base_stadium, " => ", max_stolen_base
print "Min Stolen Bases: ", min_stolen_base_stadium, " => ", min_stolen_base

STOLEN BASES by STADIUMS:

Stadium:  TEX  =>  964
Stadium:  ANA  =>  1082
Stadium:  BAL  =>  797
Stadium:  DET  =>  758
Stadium:  BOS  =>  966
Stadium:  CLE  =>  897
Stadium:  KCA  =>  935
Stadium:  OAK  =>  870
Stadium:  MIN  =>  885
Stadium:  TOR  =>  883
Stadium:  SEA  =>  871
Stadium:  TBA  =>  1140
Stadium:  CHA  =>  1036
Stadium:  NYA  =>  1064
Stadium:  SFN  =>  915
Stadium:  SLN  =>  589
Stadium:  ARI  =>  783
Stadium:  PHI  =>  981
Stadium:  COL  =>  989
Stadium:  LAN  =>  1027
Stadium:  CIN  =>  850
Stadium:  MIL  =>  929
Stadium:  HOU  =>  915
Stadium:  SDN  =>  1129
Stadium:  PIT  =>  899
Stadium:  WAS  =>  824
Stadium:  NYN  =>  1015
Stadium:  ATL  =>  848
Stadium:  CHN  =>  905
Stadium:  MIA+FLO  =>  929

Max Stolen Bases:  TBA  =>  1140
Min Stolen Bases:  SLN  =>  589

In [16]:
# init defence indifference array
def_indiff_array = [[None]*(3) for i in range(0,30)]

for i in range(0,30):
    def_indiff_array[i][0] = altitudes['home_team_id'][i]
    def_indiff_array[i][1] = altitudes['altitude'][i]
    def_indiff_array[i][2] = event_counts2[i][5]

    
# calculate min/max defence indifference (5)

print "DEFENCE INDIFFERENCE by STADIUMS: "
print " "

min_def_indiff = float('inf')
min_def_indiff_stadium = None
max_def_indiff = -1
max_def_indiff_stadium = None

for i in range(0,30):
    
    if(event_counts2[i][5] <= min_def_indiff):
        min_def_indiff = event_counts2[i][5]
        min_def_indiff_stadium = event_counts2[i][0]
        
    if(event_counts2[i][5] >= max_def_indiff):
        max_def_indiff = event_counts2[i][5]
        max_def_indiff_stadium = event_counts2[i][0]
        
    print "Stadium: ", event_counts2[i][0], " => ", event_counts2[i][5]
        
print " "
print "Max Defence Indifference: ", max_def_indiff_stadium, " => ", max_def_indiff
print "Min Defence Indifference: ", min_def_indiff_stadium, " => ", min_def_indiff

DEFENCE INDIFFERENCE by STADIUMS:

Stadium:  TEX  =>  129
Stadium:  ANA  =>  136
Stadium:  BAL  =>  77
Stadium:  DET  =>  95
Stadium:  BOS  =>  128
Stadium:  CLE  =>  101
Stadium:  KCA  =>  113
Stadium:  OAK  =>  112
Stadium:  MIN  =>  107
Stadium:  TOR  =>  85
Stadium:  SEA  =>  109
Stadium:  TBA  =>  146
Stadium:  CHA  =>  84
Stadium:  NYA  =>  118
Stadium:  SFN  =>  94
Stadium:  SLN  =>  99
Stadium:  ARI  =>  104
Stadium:  PHI  =>  111
Stadium:  COL  =>  120
Stadium:  LAN  =>  138
Stadium:  CIN  =>  110
Stadium:  MIL  =>  92
Stadium:  HOU  =>  72
Stadium:  SDN  =>  112
Stadium:  PIT  =>  82
Stadium:  WAS  =>  91
Stadium:  NYN  =>  82
Stadium:  ATL  =>  88
Stadium:  CHN  =>  120
Stadium:  MIA+FLO  =>  66

Max Defence Indifference:  TBA  =>  146
Min Defence Indifference:  MIA+FLO  =>  66

In [93]:
# init caught stealing array
caught_stealing_array = [[None]*(3) for i in range(0,30)]

for i in range(0,30):
    caught_stealing_array[i][0] = altitudes['home_team_id'][i]
    caught_stealing_array[i][1] = altitudes['altitude'][i]
    caught_stealing_array[i][2] = event_counts2[i][6]


# calculate min/max caught stealing (6)

print "CAUGHT STEALING by STADIUMS: "
print " "

min_caught_stealing = float('inf')
min_caught_stealing_stadium = None
max_caught_stealing = -1
max_caught_stealing_stadium = None

for i in range(0,30):
    
    if(event_counts2[i][6] <= min_caught_stealing):
        min_caught_stealing = event_counts2[i][6]
        min_caught_stealing_stadium = event_counts2[i][0]
        
    if(event_counts2[i][6] >= max_caught_stealing):
        max_caught_stealing = event_counts2[i][6]
        max_caught_stealing_stadium = event_counts2[i][0]
        
    print "Stadium: ", event_counts2[i][0], " => ", event_counts2[i][6]
        
print " "
print "Max Caught Stealing: ", max_caught_stealing_stadium, " => ", max_caught_stealing
print "Min Caught Stealing: ", min_caught_stealing_stadium, " => ", min_caught_stealing

CAUGHT STEALING by STADIUMS:

Stadium:  TEX  =>  283
Stadium:  ANA  =>  340
Stadium:  BAL  =>  279
Stadium:  DET  =>  272
Stadium:  BOS  =>  213
Stadium:  CLE  =>  298
Stadium:  KCA  =>  302
Stadium:  OAK  =>  217
Stadium:  MIN  =>  251
Stadium:  TOR  =>  213
Stadium:  SEA  =>  305
Stadium:  TBA  =>  334
Stadium:  CHA  =>  291
Stadium:  NYA  =>  264
Stadium:  SFN  =>  308
Stadium:  SLN  =>  266
Stadium:  ARI  =>  243
Stadium:  PHI  =>  225
Stadium:  COL  =>  259
Stadium:  LAN  =>  318
Stadium:  CIN  =>  267
Stadium:  MIL  =>  255
Stadium:  HOU  =>  282
Stadium:  SDN  =>  300
Stadium:  PIT  =>  295
Stadium:  WAS  =>  257
Stadium:  NYN  =>  241
Stadium:  ATL  =>  259
Stadium:  CHN  =>  299
Stadium:  MIA+FLO  =>  298

Max Caught Stealing:  ANA  =>  340
Min Caught Stealing:  TOR  =>  213

In [94]:
# init pickoff array
pickoff_array = [[None]*(3) for i in range(0,30)]

for i in range(0,30):
    pickoff_array[i][0] = altitudes['home_team_id'][i]
    pickoff_array[i][1] = altitudes['altitude'][i]
    pickoff_array[i][2] = event_counts2[i][8]


# calculate min/max pickoff (8)

print "PICKOFF by STADIUMS: "
print " "

min_pickoff = float('inf')
min_pickoff_stadium = None
max_pickoff = -1
max_pickoff_stadium = None

for i in range(0,30):
    
    if(event_counts2[i][8] <= min_pickoff):
        min_pickoff = event_counts2[i][8]
        min_pickoff_stadium = event_counts2[i][0]
        
    if(event_counts2[i][8] >= max_pickoff):
        max_pickoff = event_counts2[i][8]
        max_pickoff_stadium = event_counts2[i][0]
        
    print "Stadium: ", event_counts2[i][0], " => ", event_counts2[i][8]
        
print " "
print "Max Pickoff: ", max_pickoff_stadium, " => ", max_pickoff
print "Min Pickoff: ", min_pickoff_stadium, " => ", min_pickoff

PICKOFF by STADIUMS:

Stadium:  TEX  =>  194
Stadium:  ANA  =>  233
Stadium:  BAL  =>  133
Stadium:  DET  =>  227
Stadium:  BOS  =>  169
Stadium:  CLE  =>  178
Stadium:  KCA  =>  239
Stadium:  OAK  =>  179
Stadium:  MIN  =>  178
Stadium:  TOR  =>  202
Stadium:  SEA  =>  189
Stadium:  TBA  =>  202
Stadium:  CHA  =>  237
Stadium:  NYA  =>  161
Stadium:  SFN  =>  175
Stadium:  SLN  =>  160
Stadium:  ARI  =>  221
Stadium:  PHI  =>  151
Stadium:  COL  =>  229
Stadium:  LAN  =>  188
Stadium:  CIN  =>  193
Stadium:  MIL  =>  215
Stadium:  HOU  =>  171
Stadium:  SDN  =>  213
Stadium:  PIT  =>  233
Stadium:  WAS  =>  173
Stadium:  NYN  =>  151
Stadium:  ATL  =>  164
Stadium:  CHN  =>  172
Stadium:  MIA+FLO  =>  189

Max Pickoff:  KCA  =>  239
Min Pickoff:  BAL  =>  133

In [95]:
# init wild pitch array
wild_pitch_array = [[None]*(3) for i in range(0,30)]

for i in range(0,30):
    wild_pitch_array[i][0] = altitudes['home_team_id'][i]
    wild_pitch_array[i][1] = altitudes['altitude'][i]
    wild_pitch_array[i][2] = event_counts2[i][9]


# calculate min/max wild pitch (9)

print "WILD PITCH by STADIUMS: "
print " "

min_wild_pitch = float('inf')
min_wild_pitch_stadium = None
max_wild_pitch = -1
max_wild_pitch_stadium = None

for i in range(0,30):
    
    if(event_counts2[i][9] <= min_wild_pitch):
        min_wild_pitch = event_counts2[i][9]
        min_wild_pitch_stadium = event_counts2[i][0]
        
    if(event_counts2[i][9] >= max_wild_pitch):
        max_wild_pitch = event_counts2[i][9]
        max_wild_pitch_stadium = event_counts2[i][0]
        
    print "Stadium: ", event_counts2[i][0], " => ", event_counts2[i][9]
        
print " "
print "Max Wild Pitch: ", max_wild_pitch_stadium, " => ", max_wild_pitch
print "Min Wild Pitch: ", min_wild_pitch_stadium, " => ", min_wild_pitch

WILD PITCH by STADIUMS:

Stadium:  TEX  =>  614
Stadium:  ANA  =>  601
Stadium:  BAL  =>  452
Stadium:  DET  =>  577
Stadium:  BOS  =>  561
Stadium:  CLE  =>  545
Stadium:  KCA  =>  660
Stadium:  OAK  =>  491
Stadium:  MIN  =>  528
Stadium:  TOR  =>  455
Stadium:  SEA  =>  568
Stadium:  TBA  =>  577
Stadium:  CHA  =>  618
Stadium:  NYA  =>  542
Stadium:  SFN  =>  577
Stadium:  SLN  =>  494
Stadium:  ARI  =>  617
Stadium:  PHI  =>  463
Stadium:  COL  =>  556
Stadium:  LAN  =>  496
Stadium:  CIN  =>  512
Stadium:  MIL  =>  562
Stadium:  HOU  =>  483
Stadium:  SDN  =>  376
Stadium:  PIT  =>  522
Stadium:  WAS  =>  521
Stadium:  NYN  =>  430
Stadium:  ATL  =>  470
Stadium:  CHN  =>  555
Stadium:  MIA+FLO  =>  551

Max Wild Pitch:  KCA  =>  660
Min Wild Pitch:  SDN  =>  376

In [96]:
# init passed ball array
passed_ball_array = [[None]*(3) for i in range(0,30)]

for i in range(0,30):
    passed_ball_array[i][0] = altitudes['home_team_id'][i]
    passed_ball_array[i][1] = altitudes['altitude'][i]
    passed_ball_array[i][2] = event_counts2[i][10]


# calculate min/max passed ball (10)

print "PASSED BALL by STADIUMS: "
print " "

min_passed_ball = float('inf')
min_passed_ball_stadium = None
max_passed_ball = -1
max_passed_ball_stadium = None

for i in range(0,30):
    
    if(event_counts2[i][10] <= min_passed_ball):
        min_passed_ball = event_counts2[i][10]
        min_passed_ball_stadium = event_counts2[i][0]
        
    if(event_counts2[i][10] >= max_passed_ball):
        max_passed_ball = event_counts2[i][10]
        max_passed_ball_stadium = event_counts2[i][0]
        
    print "Stadium: ", event_counts2[i][0], " => ", event_counts2[i][10]
        
print " "
print "Max Passed Ball: ", max_passed_ball_stadium, " => ", max_passed_ball
print "Min Passed Ball: ", min_passed_ball_stadium, " => ", min_passed_ball

PASSED BALL by STADIUMS:

Stadium:  TEX  =>  98
Stadium:  ANA  =>  87
Stadium:  BAL  =>  96
Stadium:  DET  =>  87
Stadium:  BOS  =>  161
Stadium:  CLE  =>  122
Stadium:  KCA  =>  101
Stadium:  OAK  =>  107
Stadium:  MIN  =>  94
Stadium:  TOR  =>  134
Stadium:  SEA  =>  107
Stadium:  TBA  =>  119
Stadium:  CHA  =>  113
Stadium:  NYA  =>  105
Stadium:  SFN  =>  87
Stadium:  SLN  =>  97
Stadium:  ARI  =>  108
Stadium:  PHI  =>  112
Stadium:  COL  =>  106
Stadium:  LAN  =>  69
Stadium:  CIN  =>  91
Stadium:  MIL  =>  60
Stadium:  HOU  =>  114
Stadium:  SDN  =>  128
Stadium:  PIT  =>  85
Stadium:  WAS  =>  95
Stadium:  NYN  =>  99
Stadium:  ATL  =>  103
Stadium:  CHN  =>  109
Stadium:  MIA+FLO  =>  118

Max Passed Ball:  BOS  =>  161
Min Passed Ball:  MIL  =>  60

In [97]:
# init balk array
balk_array = [[None]*(3) for i in range(0,30)]

for i in range(0,30):
    balk_array[i][0] = altitudes['home_team_id'][i]
    balk_array[i][1] = altitudes['altitude'][i]
    balk_array[i][2] = event_counts2[i][11]


# calculate min/max balk (11)

print "BALK by STADIUMS: "
print " "

min_balk = float('inf')
min_balk_stadium = None
max_balk = -1
max_balk_stadium = None

for i in range(0,30):
    
    if(event_counts2[i][11] <= min_balk):
        min_balk = event_counts2[i][11]
        min_balk_stadium = event_counts2[i][0]
        
    if(event_counts2[i][11] >= max_balk):
        max_balk = event_counts2[i][11]
        max_balk_stadium = event_counts2[i][0]
        
    print "Stadium: ", event_counts2[i][0], " => ", event_counts2[i][11]
        
print " "
print "Max Balk: ", max_balk_stadium, " => ", max_balk
print "Min Balk: ", min_balk_stadium, " => ", min_balk

BALK by STADIUMS:

Stadium:  TEX  =>  46
Stadium:  ANA  =>  44
Stadium:  BAL  =>  60
Stadium:  DET  =>  64
Stadium:  BOS  =>  61
Stadium:  CLE  =>  49
Stadium:  KCA  =>  76
Stadium:  OAK  =>  49
Stadium:  MIN  =>  54
Stadium:  TOR  =>  47
Stadium:  SEA  =>  50
Stadium:  TBA  =>  52
Stadium:  CHA  =>  57
Stadium:  NYA  =>  64
Stadium:  SFN  =>  44
Stadium:  SLN  =>  41
Stadium:  ARI  =>  56
Stadium:  PHI  =>  63
Stadium:  COL  =>  69
Stadium:  LAN  =>  57
Stadium:  CIN  =>  59
Stadium:  MIL  =>  53
Stadium:  HOU  =>  62
Stadium:  SDN  =>  51
Stadium:  PIT  =>  42
Stadium:  WAS  =>  63
Stadium:  NYN  =>  59
Stadium:  ATL  =>  65
Stadium:  CHN  =>  38
Stadium:  MIA+FLO  =>  54

Max Balk:  KCA  =>  76
Min Balk:  CHN  =>  38

In [98]:
# init other advance array
other_adv_array = [[None]*(3) for i in range(0,30)]

for i in range(0,30):
    other_adv_array[i][0] = altitudes['home_team_id'][i]
    other_adv_array[i][1] = altitudes['altitude'][i]
    other_adv_array[i][2] = event_counts2[i][12]


# calculate min/max other advance (12)

print "OTHER ADVANCE by STADIUMS: "
print " "

min_other_adv = float('inf')
min_other_adv_stadium = None
max_other_adv = -1
max_other_adv_stadium = None

for i in range(0,30):
    
    if(event_counts2[i][12] <= min_other_adv):
        min_other_adv = event_counts2[i][12]
        min_other_adv_stadium = event_counts2[i][0]
        
    if(event_counts2[i][12] >= max_other_adv):
        max_other_adv = event_counts2[i][12]
        max_other_adv_stadium = event_counts2[i][0]
        
    print "Stadium: ", event_counts2[i][0], " => ", event_counts2[i][12]
        
print " "
print "Max Other Advance: ", max_other_adv_stadium, " => ", max_other_adv
print "Min Other Advance: ", min_other_adv_stadium, " => ", min_other_adv

OTHER ADVANCE by STADIUMS:

Stadium:  TEX  =>  24
Stadium:  ANA  =>  28
Stadium:  BAL  =>  20
Stadium:  DET  =>  35
Stadium:  BOS  =>  24
Stadium:  CLE  =>  27
Stadium:  KCA  =>  37
Stadium:  OAK  =>  27
Stadium:  MIN  =>  23
Stadium:  TOR  =>  26
Stadium:  SEA  =>  27
Stadium:  TBA  =>  33
Stadium:  CHA  =>  34
Stadium:  NYA  =>  26
Stadium:  SFN  =>  24
Stadium:  SLN  =>  17
Stadium:  ARI  =>  27
Stadium:  PHI  =>  27
Stadium:  COL  =>  38
Stadium:  LAN  =>  20
Stadium:  CIN  =>  18
Stadium:  MIL  =>  22
Stadium:  HOU  =>  35
Stadium:  SDN  =>  27
Stadium:  PIT  =>  28
Stadium:  WAS  =>  27
Stadium:  NYN  =>  25
Stadium:  ATL  =>  17
Stadium:  CHN  =>  36
Stadium:  MIA+FLO  =>  33

Max Other Advance:  COL  =>  38
Min Other Advance:  ATL  =>  17

In [99]:
# init foul error array
foul_error_array = [[None]*(3) for i in range(0,30)]

for i in range(0,30):
    foul_error_array[i][0] = altitudes['home_team_id'][i]
    foul_error_array[i][1] = altitudes['altitude'][i]
    foul_error_array[i][2] = event_counts2[i][13]


# calculate min/max foul error (13)

print "FOUL ERROR by STADIUMS: "
print " "

min_foul_error = float('inf')
min_foul_error_stadium = None
max_foul_error = -1
max_foul_error_stadium = None

for i in range(0,30):
    
    if(event_counts2[i][13] <= min_foul_error):
        min_foul_error = event_counts2[i][13]
        min_foul_error_stadium = event_counts2[i][0]
        
    if(event_counts2[i][13] >= max_foul_error):
        max_foul_error = event_counts2[i][13]
        max_foul_error_stadium = event_counts2[i][0]
        
    print "Stadium: ", event_counts2[i][0], " => ", event_counts2[i][13]
        
print " "
print "Max Foul Error: ", max_foul_error_stadium, " => ", max_foul_error
print "Min Foul Error: ", min_foul_error_stadium, " => ", min_foul_error

FOUL ERROR by STADIUMS:

Stadium:  TEX  =>  13
Stadium:  ANA  =>  19
Stadium:  BAL  =>  19
Stadium:  DET  =>  29
Stadium:  BOS  =>  18
Stadium:  CLE  =>  9
Stadium:  KCA  =>  20
Stadium:  OAK  =>  41
Stadium:  MIN  =>  6
Stadium:  TOR  =>  18
Stadium:  SEA  =>  13
Stadium:  TBA  =>  12
Stadium:  CHA  =>  24
Stadium:  NYA  =>  12
Stadium:  SFN  =>  7
Stadium:  SLN  =>  13
Stadium:  ARI  =>  8
Stadium:  PHI  =>  25
Stadium:  COL  =>  18
Stadium:  LAN  =>  19
Stadium:  CIN  =>  12
Stadium:  MIL  =>  12
Stadium:  HOU  =>  11
Stadium:  SDN  =>  7
Stadium:  PIT  =>  12
Stadium:  WAS  =>  18
Stadium:  NYN  =>  24
Stadium:  ATL  =>  9
Stadium:  CHN  =>  18
Stadium:  MIA+FLO  =>  18

Max Foul Error:  OAK  =>  41
Min Foul Error:  MIN  =>  6

In [100]:
# init walk array
walk_array = [[None]*(3) for i in range(0,30)]

for i in range(0,30):
    walk_array[i][0] = altitudes['home_team_id'][i]
    walk_array[i][1] = altitudes['altitude'][i]
    walk_array[i][2] = event_counts2[i][14]


# calculate min/max walk (14)

print "WALK by STADIUMS: "
print " "

min_walk = float('inf')
min_walk_stadium = None
max_walk = -1
max_walk_stadium = None

for i in range(0,30):
    
    if(event_counts2[i][14] <= min_walk):
        min_walk = event_counts2[i][14]
        min_walk_stadium = event_counts2[i][0]
        
    if(event_counts2[i][14] >= max_walk):
        max_walk = event_counts2[i][14]
        max_walk_stadium = event_counts2[i][0]
        
    print "Stadium: ", event_counts2[i][0], " => ", event_counts2[i][14]
        
print " "
print "Max Walk: ", max_walk_stadium, " => ", max_walk
print "Min Walk: ", min_walk_stadium, " => ", min_walk

WALK by STADIUMS:

Stadium:  TEX  =>  5356
Stadium:  ANA  =>  4793
Stadium:  BAL  =>  5224
Stadium:  DET  =>  5048
Stadium:  BOS  =>  5706
Stadium:  CLE  =>  5323
Stadium:  KCA  =>  4986
Stadium:  OAK  =>  5476
Stadium:  MIN  =>  4620
Stadium:  TOR  =>  5202
Stadium:  SEA  =>  4858
Stadium:  TBA  =>  5517
Stadium:  CHA  =>  5185
Stadium:  NYA  =>  5557
Stadium:  SFN  =>  4950
Stadium:  SLN  =>  4947
Stadium:  ARI  =>  5196
Stadium:  PHI  =>  5025
Stadium:  COL  =>  5338
Stadium:  LAN  =>  4938
Stadium:  CIN  =>  5309
Stadium:  MIL  =>  5284
Stadium:  HOU  =>  4984
Stadium:  SDN  =>  5291
Stadium:  PIT  =>  4951
Stadium:  WAS  =>  4966
Stadium:  NYN  =>  5221
Stadium:  ATL  =>  5323
Stadium:  CHN  =>  5393
Stadium:  MIA+FLO  =>  5437

Max Walk:  BOS  =>  5706
Min Walk:  MIN  =>  4620

In [101]:
# init intentional walks array
int_walks_array = [[None]*(3) for i in range(0,30)]

for i in range(0,30):
    int_walks_array[i][0] = altitudes['home_team_id'][i]
    int_walks_array[i][1] = altitudes['altitude'][i]
    int_walks_array[i][2] = event_counts2[i][15]


# calculate min/max intentional walks (15)

print "INTENTIONAL WALKS by STADIUMS: "
print " "

min_int_walks = float('inf')
min_int_walks_stadium = None
max_int_walks = -1
max_int_walks_stadium = None

for i in range(0,30):
    
    if(event_counts2[i][15] <= min_int_walks):
        min_int_walks = event_counts2[i][15]
        min_int_walks_stadium = event_counts2[i][0]
        
    if(event_counts2[i][15] >= max_int_walks):
        max_int_walks = event_counts2[i][15]
        max_int_walks_stadium = event_counts2[i][0]
        
    print "Stadium: ", event_counts2[i][0], " => ", event_counts2[i][15]
        
print " "
print "Max Intentional Walks: ", max_int_walks_stadium, " => ", max_int_walks
print "Min Intentional Walks: ", min_int_walks_stadium, " => ", min_int_walks

INTENTIONAL WALKS by STADIUMS:

Stadium:  TEX  =>  319
Stadium:  ANA  =>  392
Stadium:  BAL  =>  335
Stadium:  DET  =>  420
Stadium:  BOS  =>  348
Stadium:  CLE  =>  343
Stadium:  KCA  =>  306
Stadium:  OAK  =>  326
Stadium:  MIN  =>  343
Stadium:  TOR  =>  294
Stadium:  SEA  =>  376
Stadium:  TBA  =>  338
Stadium:  CHA  =>  378
Stadium:  NYA  =>  337
Stadium:  SFN  =>  506
Stadium:  SLN  =>  492
Stadium:  ARI  =>  446
Stadium:  PHI  =>  547
Stadium:  COL  =>  542
Stadium:  LAN  =>  542
Stadium:  CIN  =>  473
Stadium:  MIL  =>  435
Stadium:  HOU  =>  428
Stadium:  SDN  =>  486
Stadium:  PIT  =>  486
Stadium:  WAS  =>  500
Stadium:  NYN  =>  566
Stadium:  ATL  =>  581
Stadium:  CHN  =>  417
Stadium:  MIA+FLO  =>  582

Max Intentional Walks:  MIA+FLO  =>  582
Min Intentional Walks:  TOR  =>  294

In [102]:
# init hit by pitch array
hit_by_pitch_array = [[None]*(3) for i in range(0,30)]

for i in range(0,30):
    hit_by_pitch_array[i][0] = altitudes['home_team_id'][i]
    hit_by_pitch_array[i][1] = altitudes['altitude'][i]
    hit_by_pitch_array[i][2] = event_counts2[i][16]


# calculate min/max hit by pitch (16)

print "HIT BY PITCH by STADIUMS: "
print " "

min_hit_by_pitch = float('inf')
min_hit_by_pitch_stadium = None
max_hit_by_pitch = -1
max_hit_by_pitch_stadium = None

for i in range(0,30):
    
    if(event_counts2[i][16] <= min_hit_by_pitch):
        min_hit_by_pitch = event_counts2[i][16]
        min_hit_by_pitch_stadium = event_counts2[i][0]
        
    if(event_counts2[i][16] >= max_hit_by_pitch):
        max_hit_by_pitch = event_counts2[i][16]
        max_hit_by_pitch_stadium = event_counts2[i][0]
        
    print "Stadium: ", event_counts2[i][0], " => ", event_counts2[i][16]
        
print " "
print "Max Hit By Pitches: ", max_hit_by_pitch_stadium, " => ", max_hit_by_pitch
print "Min Hit By Pitches: ", min_hit_by_pitch_stadium, " => ", min_hit_by_pitch

HIT BY PITCH by STADIUMS:

Stadium:  TEX  =>  646
Stadium:  ANA  =>  558
Stadium:  BAL  =>  598
Stadium:  DET  =>  526
Stadium:  BOS  =>  662
Stadium:  CLE  =>  603
Stadium:  KCA  =>  598
Stadium:  OAK  =>  486
Stadium:  MIN  =>  499
Stadium:  TOR  =>  662
Stadium:  SEA  =>  537
Stadium:  TBA  =>  673
Stadium:  CHA  =>  659
Stadium:  NYA  =>  718
Stadium:  SFN  =>  476
Stadium:  SLN  =>  640
Stadium:  ARI  =>  585
Stadium:  PHI  =>  698
Stadium:  COL  =>  582
Stadium:  LAN  =>  546
Stadium:  CIN  =>  683
Stadium:  MIL  =>  608
Stadium:  HOU  =>  604
Stadium:  SDN  =>  493
Stadium:  PIT  =>  712
Stadium:  WAS  =>  606
Stadium:  NYN  =>  595
Stadium:  ATL  =>  518
Stadium:  CHN  =>  638
Stadium:  MIA+FLO  =>  607

Max Hit By Pitches:  NYA  =>  718
Min Hit By Pitches:  SFN  =>  476

In [103]:
# init interference array
interference_array = [[None]*(3) for i in range(0,30)]

for i in range(0,30):
    interference_array[i][0] = altitudes['home_team_id'][i]
    interference_array[i][1] = altitudes['altitude'][i]
    interference_array[i][2] = event_counts2[i][17]


# calculate min/max interference(17)

print "INTERFERENCE by STADIUMS: "
print " "

min_interference = float('inf')
min_interference_stadium = None
max_interference = -1
max_interference_stadium = None

for i in range(0,30):
    
    if(event_counts2[i][17] <= min_interference):
        min_interference = event_counts2[i][17]
        min_interference_stadium = event_counts2[i][0]
        
    if(event_counts2[i][17] >= max_interference):
        max_interference = event_counts2[i][17]
        max_interference_stadium = event_counts2[i][0]
        
    print "Stadium: ", event_counts2[i][0], " => ", event_counts2[i][17]
        
print " "
print "Max Interferences: ", max_interference_stadium, " => ", max_interference
print "Min Interferences: ", min_interference_stadium, " => ", min_interference

INTERFERENCE by STADIUMS:

Stadium:  TEX  =>  18
Stadium:  ANA  =>  19
Stadium:  BAL  =>  11
Stadium:  DET  =>  7
Stadium:  BOS  =>  7
Stadium:  CLE  =>  5
Stadium:  KCA  =>  8
Stadium:  OAK  =>  4
Stadium:  MIN  =>  1
Stadium:  TOR  =>  9
Stadium:  SEA  =>  4
Stadium:  TBA  =>  17
Stadium:  CHA  =>  7
Stadium:  NYA  =>  10
Stadium:  SFN  =>  10
Stadium:  SLN  =>  5
Stadium:  ARI  =>  8
Stadium:  PHI  =>  9
Stadium:  COL  =>  8
Stadium:  LAN  =>  9
Stadium:  CIN  =>  9
Stadium:  MIL  =>  8
Stadium:  HOU  =>  9
Stadium:  SDN  =>  9
Stadium:  PIT  =>  5
Stadium:  WAS  =>  4
Stadium:  NYN  =>  5
Stadium:  ATL  =>  19
Stadium:  CHN  =>  5
Stadium:  MIA+FLO  =>  8

Max Interferences:  ATL  =>  19
Min Interferences:  MIN  =>  1

In [104]:
# init error array
error_array = [[None]*(3) for i in range(0,30)]

for i in range(0,30):
    error_array[i][0] = altitudes['home_team_id'][i]
    error_array[i][1] = altitudes['altitude'][i]
    error_array[i][2] = event_counts2[i][18]


# calculate min/max error (18)

print "ERRORS by STADIUMS: "
print " "

min_errors = float('inf')
min_errors_stadium = None
max_errors = -1
max_errors_stadium = None

for i in range(0,30):
    
    if(event_counts2[i][18] <= min_errors):
        min_errors = event_counts2[i][18]
        min_errors_stadium = event_counts2[i][0]
        
    if(event_counts2[i][18] >= max_errors):
        max_errors = event_counts2[i][18]
        max_errors_stadium = event_counts2[i][0]
        
    print "Stadium: ", event_counts2[i][0], " => ", event_counts2[i][18]
        
print " "
print "Max Errors: ", max_errors_stadium, " => ", max_errors
print "Min Errors: ", min_errors_stadium, " => ", min_errors

ERRORS by STADIUMS:

Stadium:  TEX  =>  706
Stadium:  ANA  =>  611
Stadium:  BAL  =>  539
Stadium:  DET  =>  590
Stadium:  BOS  =>  604
Stadium:  CLE  =>  607
Stadium:  KCA  =>  567
Stadium:  OAK  =>  611
Stadium:  MIN  =>  571
Stadium:  TOR  =>  576
Stadium:  SEA  =>  563
Stadium:  TBA  =>  509
Stadium:  CHA  =>  615
Stadium:  NYA  =>  608
Stadium:  SFN  =>  589
Stadium:  SLN  =>  620
Stadium:  ARI  =>  546
Stadium:  PHI  =>  651
Stadium:  COL  =>  608
Stadium:  LAN  =>  583
Stadium:  CIN  =>  548
Stadium:  MIL  =>  642
Stadium:  HOU  =>  576
Stadium:  SDN  =>  509
Stadium:  PIT  =>  641
Stadium:  WAS  =>  612
Stadium:  NYN  =>  620
Stadium:  ATL  =>  635
Stadium:  CHN  =>  677
Stadium:  MIA+FLO  =>  580

Max Errors:  TEX  =>  706
Min Errors:  SDN  =>  509

In [105]:
# init fielder's choice array
field_choice_array = [[None]*(3) for i in range(0,30)]

for i in range(0,30):
    field_choice_array[i][0] = altitudes['home_team_id'][i]
    field_choice_array[i][1] = altitudes['altitude'][i]
    field_choice_array[i][2] = event_counts2[i][19]


# calculate min/max fielder's choice (19)

print "FIELDER'S CHOICE by STADIUMS: "
print " "

min_field_choice = float('inf')
min_field_choice_stadium = None
max_field_choice = -1
max_field_choice_stadium = None

for i in range(0,30):
    
    if(event_counts2[i][19] <= min_field_choice):
        min_field_choice = event_counts2[i][19]
        min_field_choice_stadium = event_counts2[i][0]
        
    if(event_counts2[i][19] >= max_field_choice):
        max_field_choice = event_counts2[i][19]
        max_field_choice_stadium = event_counts2[i][0]
        
    print "Stadium: ", event_counts2[i][0], " => ", event_counts2[i][19]
        
print " "
print "Max Fielder's Choice: ", max_field_choice_stadium, " => ", max_field_choice
print "Min Fielder's Choice: ", min_field_choice_stadium, " => ", min_field_choice

FIELDER'S CHOICE by STADIUMS:

Stadium:  TEX  =>  194
Stadium:  ANA  =>  217
Stadium:  BAL  =>  148
Stadium:  DET  =>  174
Stadium:  BOS  =>  156
Stadium:  CLE  =>  189
Stadium:  KCA  =>  206
Stadium:  OAK  =>  191
Stadium:  MIN  =>  204
Stadium:  TOR  =>  158
Stadium:  SEA  =>  185
Stadium:  TBA  =>  142
Stadium:  CHA  =>  132
Stadium:  NYA  =>  156
Stadium:  SFN  =>  213
Stadium:  SLN  =>  217
Stadium:  ARI  =>  193
Stadium:  PHI  =>  163
Stadium:  COL  =>  217
Stadium:  LAN  =>  170
Stadium:  CIN  =>  200
Stadium:  MIL  =>  185
Stadium:  HOU  =>  189
Stadium:  SDN  =>  188
Stadium:  PIT  =>  223
Stadium:  WAS  =>  189
Stadium:  NYN  =>  179
Stadium:  ATL  =>  157
Stadium:  CHN  =>  201
Stadium:  MIA+FLO  =>  215

Max Fielder's Choice:  PIT  =>  223
Min Fielder's Choice:  CHA  =>  132

In [106]:
# init singles array
singles_array = [[None]*(3) for i in range(0,30)]

for i in range(0,30):
    singles_array[i][0] = altitudes['home_team_id'][i]
    singles_array[i][1] = altitudes['altitude'][i]
    singles_array[i][2] = event_counts2[i][20]


# calculate min/max singles(20)

print "SINGLES by STADIUMS: "
print " "

min_single = float('inf')
min_single_stadium = None
max_single = -1
max_single_stadium = None

for i in range(0,30):
    
    if(event_counts2[i][20] <= min_single):
        min_single = event_counts2[i][20]
        min_single_stadium = event_counts2[i][0]
        
    if(event_counts2[i][20] >= max_single):
        max_single = event_counts2[i][20]
        max_single_stadium = event_counts2[i][0]
        
    print "Stadium: ", event_counts2[i][0], " => ", event_counts2[i][20]
        
print " "
print "Max Singles: ", max_single_stadium, " => ", max_single
print "Min Singles: ", min_single_stadium, " => ", min_single

SINGLES by STADIUMS:

Stadium:  TEX  =>  11039
Stadium:  ANA  =>  10865
Stadium:  BAL  =>  11011
Stadium:  DET  =>  11227
Stadium:  BOS  =>  10648
Stadium:  CLE  =>  10598
Stadium:  KCA  =>  11369
Stadium:  OAK  =>  10179
Stadium:  MIN  =>  11307
Stadium:  TOR  =>  9829
Stadium:  SEA  =>  10409
Stadium:  TBA  =>  9968
Stadium:  CHA  =>  10520
Stadium:  NYA  =>  10657
Stadium:  SFN  =>  10314
Stadium:  SLN  =>  10944
Stadium:  ARI  =>  10316
Stadium:  PHI  =>  10320
Stadium:  COL  =>  11815
Stadium:  LAN  =>  10388
Stadium:  CIN  =>  10152
Stadium:  MIL  =>  9917
Stadium:  HOU  =>  10194
Stadium:  SDN  =>  9761
Stadium:  PIT  =>  10869
Stadium:  WAS  =>  10544
Stadium:  NYN  =>  10135
Stadium:  ATL  =>  10544
Stadium:  CHN  =>  10057
Stadium:  MIA+FLO  =>  10585

Max Singles:  COL  =>  11815
Min Singles:  SDN  =>  9761

In [107]:
# init doubles array
doubles_array = [[None]*(3) for i in range(0,30)]

for i in range(0,30):
    doubles_array[i][0] = altitudes['home_team_id'][i]
    doubles_array[i][1] = altitudes['altitude'][i]
    doubles_array[i][2] = event_counts2[i][21]


# calculate min/max doubles (21)

print "DOUBLES by STADIUMS: "
print " "

min_doubles = float('inf')
min_doubles_stadium = None
max_doubles = -1
max_doubles_stadium = None

for i in range(0,30):
    
    if(event_counts2[i][21] <= min_doubles):
        min_doubles = event_counts2[i][21]
        min_doubles_stadium = event_counts2[i][0]
        
    if(event_counts2[i][21] >= max_doubles):
        max_doubles = event_counts2[i][21]
        max_doubles_stadium = event_counts2[i][0]
        
    print "Stadium: ", event_counts2[i][0], " => ", event_counts2[i][21]
        
print " "
print "Max Doubles: ", max_doubles_stadium, " => ", max_doubles
print "Min Doubles: ", min_doubles_stadium, " => ", min_doubles

DOUBLES by STADIUMS:

Stadium:  TEX  =>  3328
Stadium:  ANA  =>  3029
Stadium:  BAL  =>  3123
Stadium:  DET  =>  3067
Stadium:  BOS  =>  4072
Stadium:  CLE  =>  3349
Stadium:  KCA  =>  3441
Stadium:  OAK  =>  2934
Stadium:  MIN  =>  3171
Stadium:  TOR  =>  3461
Stadium:  SEA  =>  2847
Stadium:  TBA  =>  2886
Stadium:  CHA  =>  2876
Stadium:  NYA  =>  3004
Stadium:  SFN  =>  3059
Stadium:  SLN  =>  3092
Stadium:  ARI  =>  3498
Stadium:  PHI  =>  3194
Stadium:  COL  =>  3652
Stadium:  LAN  =>  2902
Stadium:  CIN  =>  3179
Stadium:  MIL  =>  3186
Stadium:  HOU  =>  3062
Stadium:  SDN  =>  2631
Stadium:  PIT  =>  3266
Stadium:  WAS  =>  3105
Stadium:  NYN  =>  2976
Stadium:  ATL  =>  2995
Stadium:  CHN  =>  3183
Stadium:  MIA+FLO  =>  3107

Max Doubles:  BOS  =>  4072
Min Doubles:  SDN  =>  2631

In [108]:
# init triples array
triples_array = [[None]*(3) for i in range(0,30)]

for i in range(0,30):
    triples_array[i][0] = altitudes['home_team_id'][i]
    triples_array[i][1] = altitudes['altitude'][i]
    triples_array[i][2] = event_counts2[i][22]


# calculate min/max triples (22)

print "TRIPLES INDIFFERENCE by STADIUMS: "
print " "

min_triples = float('inf')
min_triples_stadium = None
max_triples = -1
max_triples_stadium = None

for i in range(0,30):
    
    if(event_counts2[i][22] <= min_triples):
        min_triples = event_counts2[i][22]
        min_triples_stadium = event_counts2[i][0]
        
    if(event_counts2[i][22] >= max_triples):
        max_triples = event_counts2[i][22]
        max_triples_stadium = event_counts2[i][0]
        
    print "Stadium: ", event_counts2[i][0], " => ", event_counts2[i][22]
        
print " "
print "Max Triples: ", max_triples_stadium, " => ", max_triples
print "Min Triples: ", min_triples_stadium, " => ", min_triples

TRIPLES INDIFFERENCE by STADIUMS:

Stadium:  TEX  =>  356
Stadium:  ANA  =>  246
Stadium:  BAL  =>  206
Stadium:  DET  =>  492
Stadium:  BOS  =>  292
Stadium:  CLE  =>  213
Stadium:  KCA  =>  442
Stadium:  OAK  =>  284
Stadium:  MIN  =>  374
Stadium:  TOR  =>  312
Stadium:  SEA  =>  214
Stadium:  TBA  =>  361
Stadium:  CHA  =>  229
Stadium:  NYA  =>  207
Stadium:  SFN  =>  470
Stadium:  SLN  =>  282
Stadium:  ARI  =>  508
Stadium:  PHI  =>  322
Stadium:  COL  =>  576
Stadium:  LAN  =>  208
Stadium:  CIN  =>  237
Stadium:  MIL  =>  322
Stadium:  HOU  =>  353
Stadium:  SDN  =>  384
Stadium:  PIT  =>  297
Stadium:  WAS  =>  279
Stadium:  NYN  =>  303
Stadium:  ATL  =>  304
Stadium:  CHN  =>  345
Stadium:  MIA+FLO  =>  442

Max Triples:  COL  =>  576
Min Triples:  BAL  =>  206

In [109]:
# init home runs array
home_runs_array = [[None]*(3) for i in range(0,30)]

for i in range(0,30):
    home_runs_array[i][0] = altitudes['home_team_id'][i]
    home_runs_array[i][1] = altitudes['altitude'][i]
    home_runs_array[i][2] = event_counts2[i][23]


# calculate min/max home runs (23)

print "HOME RUNS by STADIUMS: "
print " "

min_home_runs = float('inf')
min_home_runs_stadium = None
max_home_runs = -1
max_home_runs_stadium = None

for i in range(0,30):
    
    if(event_counts2[i][23] <= min_home_runs):
        min_home_runs = event_counts2[i][23]
        min_home_runs_stadium = event_counts2[i][0]
        
    if(event_counts2[i][23] >= max_home_runs):
        max_home_runs = event_counts2[i][23]
        max_home_runs_stadium = event_counts2[i][0]
        
    print "Stadium: ", event_counts2[i][0], " => ", event_counts2[i][23]
        
print " "
print "Max Home Runs: ", max_home_runs_stadium, " => ", max_home_runs
print "Min Home Runs: ", min_home_runs_stadium, " => ", min_home_runs

HOME RUNS by STADIUMS:

Stadium:  TEX  =>  2069
Stadium:  ANA  =>  1641
Stadium:  BAL  =>  2211
Stadium:  DET  =>  1811
Stadium:  BOS  =>  1767
Stadium:  CLE  =>  1696
Stadium:  KCA  =>  1452
Stadium:  OAK  =>  1518
Stadium:  MIN  =>  1603
Stadium:  TOR  =>  2124
Stadium:  SEA  =>  1593
Stadium:  TBA  =>  1799
Stadium:  CHA  =>  2148
Stadium:  NYA  =>  2222
Stadium:  SFN  =>  1260
Stadium:  SLN  =>  1492
Stadium:  ARI  =>  1896
Stadium:  PHI  =>  2045
Stadium:  COL  =>  2035
Stadium:  LAN  =>  1546
Stadium:  CIN  =>  2243
Stadium:  MIL  =>  2082
Stadium:  HOU  =>  1899
Stadium:  SDN  =>  1414
Stadium:  PIT  =>  1435
Stadium:  WAS  =>  1581
Stadium:  NYN  =>  1606
Stadium:  ATL  =>  1593
Stadium:  CHN  =>  1862
Stadium:  MIA+FLO  =>  1482

Max Home Runs:  CIN  =>  2243
Min Home Runs:  SFN  =>  1260

In [110]:
# put the previously calculated event arrays into dataframes

generic_outs_df = pd.DataFrame(data=generic_outs_array)
strikeouts_df = pd.DataFrame(data=strikeouts_array)
stolen_base_df = pd.DataFrame(data=stolen_base_array)
def_indiff_df = pd.DataFrame(data=def_indiff_array)
caught_stealing_df = pd.DataFrame(data=caught_stealing_array)
pickoff_df = pd.DataFrame(data=pickoff_array)
wild_pitch_df = pd.DataFrame(data=wild_pitch_array)
passed_ball_df = pd.DataFrame(data=passed_ball_array)
balk_df = pd.DataFrame(data=balk_array)
other_adv_df = pd.DataFrame(data=other_adv_array)
foul_error_df = pd.DataFrame(data=foul_error_array)
walk_df = pd.DataFrame(data=walk_array)
int_walks_df = pd.DataFrame(data=int_walks_array)
hit_by_pitch_df = pd.DataFrame(data=hit_by_pitch_array)
interference_df = pd.DataFrame(data=interference_array)
error_df = pd.DataFrame(data=error_array)
field_choice_df = pd.DataFrame(data=field_choice_array)
singles_df = pd.DataFrame(data=singles_array)
doubles_df = pd.DataFrame(data=doubles_array)
triples_df = pd.DataFrame(data=triples_array)
home_runs_df = pd.DataFrame(data=home_runs_array)


# calculate the correlation for all the above dataframes
corr_array = [[None]*(2) for i in range(0,22)]

corr_array[0][0] = "generic outs correlation"
corr_array[0][1] = generic_outs_df[1].corr(generic_outs_df[2])
corr_array[1][0] = "strikeouts correlation"
corr_array[1][1] = strikeouts_df[1].corr(strikeouts_df[2])
corr_array[2][0] = "stolen bases correlation"
corr_array[2][1] = stolen_base_df[1].corr(stolen_base_df[2])
corr_array[3][0] = "defensive indifference correlation"
corr_array[3][1] = def_indiff_df[1].corr(def_indiff_df[2])
corr_array[4][0] = "caught stealing correlation"
corr_array[4][1] = caught_stealing_df[1].corr(caught_stealing_df[2])
corr_array[5][0] = "pickoff correlation"
corr_array[5][1] = pickoff_df[1].corr(pickoff_df[2])
corr_array[6][0] = "wild pitch correlation"
corr_array[6][1] = wild_pitch_df[1].corr(wild_pitch_df[2])
corr_array[7][0] = "passed ball correlation"
corr_array[7][1] = passed_ball_df[1].corr(passed_ball_df[2])
corr_array[8][0] = "balk correlation"
corr_array[8][1] = balk_df[1].corr(balk_df[2])
corr_array[9][0] = "other advance correlation"
corr_array[9][1] = other_adv_df[1].corr(other_adv_df[2])
corr_array[10][0] = "foul error correlation"
corr_array[10][1] = foul_error_df[1].corr(foul_error_df[2])
corr_array[11][0] = "walk correlation"
corr_array[11][1] = walk_df[1].corr(walk_df[2])
corr_array[12][0] = "intentional walks correlation"
corr_array[12][1] = int_walks_df[1].corr(int_walks_df[2])
corr_array[13][0] = "hit by pitch correlation"
corr_array[13][1] = hit_by_pitch_df[1].corr(hit_by_pitch_df[2])
corr_array[14][0] = "generic outs correlation"
corr_array[14][1] = generic_outs_df[1].corr(generic_outs_df[2])
corr_array[15][0] = "interference correlation"
corr_array[15][1] = interference_df[1].corr(interference_df[2])
corr_array[16][0] = "error correlation"
corr_array[16][1] = error_df[1].corr(error_df[2])
corr_array[17][0] = "fielder's choice correlation"
corr_array[17][1] = field_choice_df[1].corr(field_choice_df[2])
corr_array[18][0] = "singles correlation"
corr_array[18][1] = singles_df[1].corr(singles_df[2])
corr_array[19][0] = "doubles correlation"
corr_array[19][1] = doubles_df[1].corr(doubles_df[2])
corr_array[20][0] = "triples correlation"
corr_array[20][1] = triples_df[1].corr(triples_df[2])
corr_array[21][0] = "home runs correlation"
corr_array[21][1] = home_runs_df[1].corr(home_runs_df[2])

# Determine max correlation and print output
max_corr = -1
max_corr_attribute = None

for i in range(0,22):
    
    print corr_array[i]
    
    if(corr_array[i][1] >= max_corr):
        max_corr = corr_array[i][1]
        max_corr_attribute = corr_array[i][0]
        
print " "
print "Max Correlation: ", max_corr_attribute, " => ", max_corr

['generic outs correlation', 0.10028400221124995]
['strikeouts correlation', -0.23538299622081396]
['stolen bases correlation', -0.032911730199403119]
['defensive indifference correlation', 0.037334977920257278]
['caught stealing correlation', -0.092267659454125614]
['pickoff correlation', 0.36596479523928133]
['wild pitch correlation', 0.19127447252252155]
['passed ball correlation', -0.083901724103630462]
['balk correlation', 0.28382691038688357]
['other advance correlation', 0.28912322144266422]
['foul error correlation', -0.058625300627438308]
['walk correlation', 0.061311876474130958]
['intentional walks correlation', 0.20927974543193137]
['hit by pitch correlation', -0.047782690959377663]
['generic outs correlation', 0.10028400221124995]
['interference correlation', -0.012669906356482356]
['error correlation', 0.11718155008442371]
["fielder's choice correlation", 0.28953499667463584]
['singles correlation', 0.55564243981731887]
['doubles correlation', 0.4009113291058447]
['triples correlation', 0.51760753126962566]
['home runs correlation', 0.19931954016834602]

Max Correlation:  singles correlation  =>  0.555642439817

In [111]:
print max_corr_attribute, max_corr

singles correlation 0.555642439817

In [115]:
# print correlations in a readable fashion
new_corr_df = pd.DataFrame(corr_array)
new_corr_df.columns = ['event', 'correlation']
print new_corr_df.sort_values(by=['correlation'])

                                 event  correlation
1               strikeouts correlation    -0.235383
4          caught stealing correlation    -0.092268
7              passed ball correlation    -0.083902
10              foul error correlation    -0.058625
13            hit by pitch correlation    -0.047783
2             stolen bases correlation    -0.032912
15            interference correlation    -0.012670
3   defensive indifference correlation     0.037335
11                    walk correlation     0.061312
14            generic outs correlation     0.100284
0             generic outs correlation     0.100284
16                   error correlation     0.117182
6               wild pitch correlation     0.191274
21               home runs correlation     0.199320
12       intentional walks correlation     0.209280
8                     balk correlation     0.283827
9            other advance correlation     0.289123
17        fielder's choice correlation     0.289535
5                  pickoff correlation     0.365965
19                 doubles correlation     0.400911
20                 triples correlation     0.517608
18                 singles correlation     0.555642