In [1]:
import pandas as pd

In [ ]:
dfRetro = pd.read_csv("/Users/blaisepage/Documents/CUBoulder/DataMining/Final_Project/retrosheet-events-1970-2015/retrosheet-events-plus-woba-2005_2015.csv")
altitudes = pd.read_excel("/Users/blaisepage/Documents/CUBoulder/DataMining/Final_Project/MLB_Stadium_Altitudes.xlsx")

In [3]:
dfRetro.head()

NameError: name 'dfRetro' is not defined

In [80]:
#drop unnecessary attributes 
dfRetro = dfRetro.drop(['time_since_1900', 'wOBA_pts', 'bat_hand_cd', 'base1_run_id', 'base2_run_id', 'base3_run_id','pitch_seq_tx','po1_fld_cd', 'po2_fld_cd','pit_start_fl', 'pa_ball_ct', 'pa_strike_ct', 'bat_fate_id', 'run1_fate_id', 'run2_fate_id', 'run3_fate_id', 'battedball_cd', 'inn_new_fl', 'inn_end_fl', 'pit_hand_cd'], axis=1)

In [103]:
dfRetro

a = dfRetro.loc[dfRetro['event_runs_ct'] > 1]
a

,game_id,year_id,away_team_id,home_team_id,bat_id,pit_id,bat_home_id,event_cd,inn_ct,outs_ct,...,home_score_ct,bat_fld_cd,bat_lineup_id,rbi_ct,game_new_fl,game_end_fl,inn_runs_ct,game_pa_ct,inn_pa_ct,event_runs_ct
128,ANA200504060,2005,TEX,ANA,hidar001,donnb001,0,23,8,2,...,1,9,5,2,F,F,0,31,3,2
206,ANA200504070,2005,TEX,ANA,delld001,lackj001,0,21,5,1,...,3,7,8,2,F,F,0,16,3,2
217,ANA200504070,2005,TEX,ANA,molib001,dickr001,1,23,5,2,...,3,2,7,3,F,F,0,24,4,3
367,ANA200504090,2005,KCA,ANA,guerv001,limaj001,1,20,4,2,...,4,9,3,2,F,F,2,20,6,2
373,ANA200504090,2005,KCA,ANA,staim001,gregk001,0,23,5,2,...,7,10,4,2,F,F,0,21,3,2
419,ANA200504100,2005,KCA,ANA,gotar001,colob001,0,23,2,2,...,0,4,2,2,F,F,2,10,5,2
440,ANA200504100,2005,KCA,ANA,guerv001,andeb002,1,23,4,1,...,0,9,3,2,F,F,0,11,2,2
511,ANA200504180,2005,SEA,ANA,guerv001,selea001,1,23,3,1,...,1,9,3,2,F,F,0,11,2,2
524,ANA200504180,2005,SEA,ANA,erstd001,selea001,1,23,4,2,...,3,3,1,3,F,F,0,18,4,3
570,ANA200504190,2005,SEA,ANA,sexsr001,gregk001,0,23,1,1,...,0,10,4,3,F,F,0,3,3,3
721,ANA200504210,2005,CLE,ANA,hernj001,washj001,0,21,1,2,...,0,3,6,3,F,F,0,5,5,3
729,ANA200504210,2005,CLE,ANA,bellr002,washj001,0,23,2,1,...,0,4,2,2,F,F,0,10,2,2
878,ANA200504220,2005,OAK,ANA,hatts001,rodrf003,0,20,9,2,...,3,3,5,2,F,F,0,40,4,2
919,ANA200504230,2005,OAK,ANA,kielb001,byrdp001,0,23,5,0,...,3,9,7,3,F,F,0,15,2,3
936,ANA200504230,2005,OAK,ANA,paulj001,duchj001,1,18,5,2,...,7,2,8,0,F,F,4,25,8,2
1062,ANA200505060,2005,DET,ANA,finls001,ledew001,1,22,4,2,...,1,8,7,2,F,F,0,15,4,2
1188,ANA200505080,2005,DET,ANA,rodri001,washj001,0,22,3,0,...,0,2,2,3,F,F,0,10,3,3
1321,ANA200505100,2005,CLE,ANA,andeg001,sabac001,1,23,1,2,...,0,7,4,2,F,F,0,3,3,2
1357,ANA200505100,2005,CLE,ANA,paulj001,sabac001,1,23,5,2,...,2,2,9,2,F,F,0,17,3,2
1411,ANA200505110,2005,CLE,ANA,molij001,lee-c003,1,23,2,0,...,1,2,8,2,F,F,0,7,1,2
1490,ANA200505230,2005,CHA,ANA,kenna001,garlj001,1,21,2,2,...,0,4,9,2,F,F,0,8,4,2
1627,ANA200505250,2005,CHA,ANA,konep001,washj001,0,23,1,1,...,0,3,4,3,F,F,0,3,3,3
1752,ANA200505260,2005,CHA,ANA,mcphd001,contj002,1,23,7,2,...,1,5,7,2,F,F,0,24,3,2
1838,ANA200505270,2005,KCA,ANA,sweem002,yan-e001,0,20,9,2,...,3,3,3,1,F,F,1,38,5,3
1844,ANA200505270,2005,KCA,ANA,kenna001,woodm002,1,18,9,0,...,4,4,9,1,F,F,1,35,4,3
1880,ANA200505280,2005,KCA,ANA,finls001,jensr001,1,21,3,1,...,1,8,3,2,F,F,1,11,4,2
1893,ANA200505280,2005,KCA,ANA,figgc001,jensr001,1,20,4,1,...,4,9,1,2,F,F,1,18,4,2
1897,ANA200505280,2005,KCA,ANA,andeg001,nunel001,1,23,4,2,...,7,7,4,2,F,F,4,21,7,2
1909,ANA200505280,2005,KCA,ANA,andeg001,nunel001,1,21,5,2,...,9,7,4,3,F,F,0,30,5,3
1962,ANA200505290,2005,KCA,ANA,finls001,hernr003,1,22,3,2,...,0,10,3,3,F,F,0,11,5,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2110125,WAS201509030,2015,ATL,WAS,zimmr001,mckia001,1,20,3,2,...,7,3,4,2,F,F,0,21,5,2
2110259,WAS201509040,2015,ATL,WAS,taylm002,cunnb001,1,23,10,0,...,2,11,5,3,F,T,0,40,2,3
2110283,WAS201509050,2015,ATL,WAS,harpb003,mills001,1,23,3,2,...,2,8,3,2,F,F,2,11,5,2
2110292,WAS201509050,2015,ATL,WAS,ramow001,mills001,1,19,4,1,...,4,2,8,1,F,F,0,16,3,2
2110353,WAS201509060,2015,ATL,WAS,taylm002,banum001,1,21,2,1,...,0,8,7,2,F,F,0,6,3,2
2110356,WAS201509060,2015,ATL,WAS,wertj001,banum001,1,23,2,2,...,2,7,1,3,F,F,2,9,6,3
2110449,WAS201509070,2015,NYN,WAS,ramow001,niesj001,1,23,4,0,...,0,2,7,4,F,F,0,15,3,4
2110545,WAS201509080,2015,NYN,WAS,taylm002,harvm001,1,20,6,1,...,3,8,8,1,F,F,0,25,4,4
2110556,WAS201509080,2015,NYN,WAS,cespy001,stord001,0,21,7,2,...,7,8,2,3,F,F,2,28,7,3
2110635,WAS201509090,2015,NYN,WAS,cespy001,stord001,0,23,8,1,...,2,8,2,2,F,F,1,28,3,2
2110652,WAS201509170,2015,MIA,WAS,pradm001,roart001,0,23,1,1,...,0,5,3,2,F,F,0,2,2,2
2110664,WAS201509170,2015,MIA,WAS,desmi001,cosaj001,1,23,2,1,...,0,6,6,2,F,F,0,5,2,2
2110687,WAS201509170,2015,MIA,WAS,bourj002,roart001,0,23,5,2,...,2,3,4,3,F,F,1,21,5,3
2110718,WAS201509170,2015,MIA,WAS,desmi001,morrb002,1,20,8,2,...,2,6,6,2,F,F,0,32,5,2
2110729,WAS201509180,2015,MIA,WAS,yelic001,schem001,0,23,1,1,...,0,7,3,2,F,F,0,2,2,2
2110876,WAS201509190,2015,MIA,WAS,harpb003,barrk002,1,23,7,0,...,3,9,3,2,F,F,0,29,1,2
2110900,WAS201509200,2015,MIA,WAS,wertj001,nicoj001,1,21,1,1,...,0,7,4,2,F,F,0,3,3,2
2110942,WAS201509200,2015,MIA,WAS,moort002,nicoj001,1,23,6,2,...,4,3,7,3,F,F,1,24,5,3
2110946,WAS201509200,2015,MIA,WAS,escoy001,mcgos001,1,21,6,2,...,7,5,2,3,F,F,4,28,9,3
2110966,WAS201509200,2015,MIA,WAS,dendm001,urenj001,1,20,8,2,...,11,7,4,2,F,F,1,39,5,2
2111050,WAS201509230,2015,BAL,WAS,pears001,schem001,0,23,1,2,...,0,7,4,2,F,F,0,3,3,2
2111102,WAS201509230,2015,BAL,WAS,machm001,schem001,0,23,7,2,...,3,5,2,2,F,F,0,28,3,2
2111149,WAS201509240,2015,BAL,WAS,schoj001,roart001,0,23,4,0,...,0,4,6,2,F,F,0,14,1,2
2111185,WAS201509240,2015,BAL,WAS,wietm001,treib001,0,23,8,0,...,4,2,5,2,F,F,0,31,1,2
2111220,WAS201509250,2015,PHI,WAS,altha001,zimmj003,0,23,3,1,...,1,7,2,4,F,F,0,10,4,4
2111260,WAS201509250,2015,PHI,WAS,aschc001,martr005,0,23,8,0,...,2,5,5,2,F,F,0,31,1,2
2111431,WAS201509270,2015,PHI,WAS,franj004,jansc001,0,23,8,1,...,4,9,5,2,F,F,0,31,2,2
2111440,WAS201509270,2015,PHI,WAS,blana001,papej001,0,23,9,1,...,4,4,2,2,F,F,0,37,2,2
2111447,WAS201509270,2015,PHI,WAS,ruppc001,solis001,0,20,9,2,...,4,2,8,2,F,F,3,43,8,2
2111449,WAS201509270,2015,PHI,WAS,galvf001,solis001,0,20,9,2,...,4,6,1,2,F,F,5,45,10,2

In [57]:
#now drop any unnecessary events we don't need 
#stolen bases (4), caught stealing (6), pickoff (8), 
print(len(dfRetro))

dfRetro = dfRetro[dfRetro.event_cd != 4]
dfRetro = dfRetro[dfRetro.event_cd != 6]
dfRetro = dfRetro[dfRetro.event_cd != 8]


print(len(dfRetro))

2111526
2069898

In [ ]:
dfRetro

In [66]:
#Calculating era: need to exclude events that are errors (errors are event code 18)
events_with_altitudes = pd.merge(dfRetro, altitudes, on='home_team_id')
events_with_altitudes
runs = 0
#for index, row in events_with_altitudes.iterrows():
#    runs += row["events_with_altitudes"]

In [101]:
test = events_with_altitudes.drop_duplicates('game_id')
test
new_test = test.loc[test['event_runs_ct'] > 1]
new_test

Empty DataFrame
Columns: [game_id, year_id, away_team_id, home_team_id, bat_id, pit_id, bat_home_id, event_cd, inn_ct, outs_ct, away_score_ct, home_score_ct, bat_fld_cd, bat_lineup_id, rbi_ct, inn_runs_ct, game_pa_ct, inn_pa_ct, event_runs_ct, altitude]
Index: []

In [128]:
#g = test.groupby('game_id')
# g.head()
games_played = test.groupby('home_team_id').size()
#print(games_played)
innings_played = games_played * 9
#print (innings_played)

#dfRetro.event_run_ct = dfRetro.event_runs_ct.astype(int)

#print(games_played)
index = 0
for ii in dfRetro.home_team_id.unique():
    #total_runs[index][0] = ii
    #print(ii)
    dfTemp = dfRetro.loc[ii in dfRetro['home_team_id']]
    #print(dfTemp)
    index +=1
#print (total_runs)
dftest = dfRetro.loc['COL' in dfRetro['home_team_id']]
dftest.head()

game_id         ANA200504050
year_id                 2005
away_team_id             TEX
home_team_id             ANA
bat_id              soria001
Name: 0, dtype: object